version: "3.7"
services:
   main_service:
     build: ./main_service
     ports:
     - target: 5000
       published: 5000
     environment:
     - DATABASE_URI=
     - SECRET_KEY=
   random_genre:
     build: ./random_genre
     ports:
     - target: 5000
       published: 5001 
     environment:
     - DATABASE_URI=
     - SECRET_KEY=
   random_director:
     build: ./random_director
     ports:
     - target: 5000
       published: 5002 
     environment:
     - DATABASE_URI=
     - SECRET_KEY=
   random_master:
     build: ./random_master
     ports:
     - target: 5000
       published: 5003 
     environment:
     - DATABASE_URI=
     - SECRET_KEY=
